### ISSUE TITLE
Unable to create empty containers

### ISSUE THREAD

**Issue by jayanthrajanna** [kumarvna/terraform-azurerm-storage#11]
Hi I am trying to create storage account without the container but i get below error. Can you please help me how to create just a storage account without containers using your code. Thanks in advance.

 Error: Invalid index
│
│   on modules\storage-account\output.tf line 46, in output "container_sqlva":
│   46:   value       = "${azurerm_storage_container.container[0].id}/"
│     ├────────────────
│     │ azurerm_storage_container.container is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.

**Comment by kumarvna** [comment]
Hi, 
I am not able to reproduce this error with the module. Please try to use the latest module and test it again.  If you don't provide any container, it should work and give you an empty collection.  

```hcl
# Azure Provider configuration
provider "azurerm" {
  features {}
}

module "storage" {
  source  = "kumarvna/storage/azurerm"
  version = "2.4.0"

  # By default, this module will not create a resource group
  # proivde a name to use an existing resource group, specify the existing resource group name, 
  # and set the argument to `create_resource_group = false`. Location will be same as existing RG. 
  create_resource_group = true
  resource_group_name   = "rg-demo-internal-shared-westeurope-002"
  location              = "westeurope"
  storage_account_name  = "mystorage"

  # To enable advanced threat protection set argument to `true`
  enable_advanced_threat_protection = true

  # Adding TAG's to your Azure resources (Required)
  # ProjectName and Env are already declared above, to use them here, create a varible. 
  tags = {
    ProjectName  = "demo-internal"
    Env          = "dev"
    Owner        = "user@example.com"
    BusinessUnit = "CORP"
    ServiceClass = "Gold"
  }
}
```
