### ISSUE TITLE
allow_blob_public_access removed from storage account resource.

### ISSUE THREAD

**Issue by jorgeemir29** [kumarvna/terraform-azurerm-storage#16]
Error: Unsupported argument

  on .terraform/modules/storage/main.tf line 44, in resource "azurerm_storage_account" "storeacc":
  44:   allow_blob_public_access  = var.enable_advanced_threat_protection == true ? true : false

An argument named "allow_blob_public_access" is not expected here.

Should be migrated to>

azurerm_storage_account - (Beta) add a state migration for the renaming of allow_blob_public_access to allow_nested_items_to_be_public ([#13607](https://github.com/hashicorp/terraform-provider-azurerm/issues/13607))

**Comment by kumarvna** [comment]
With new version of Azurerm (V3.0) The field `allow_blob_public_access` will be renamed to `allow_nested_items_to_be_public` to resolve confusion about what this field does. It now removed from the main configuration to fix the issue by @xescab. 

Please use new release v2.5.0 and provide your feedback if any issues still. 👍
