### ISSUE TITLE
The argument "identity.0.type" is required, but no definition was found

### ISSUE THREAD

**Issue by Kumar1325** [kumarvna/terraform-azurerm-storage#7]
When I use the variable `identity` value to `false`, I'm getting the following error

The argument "identity.0.type" is required, but no definition was found

**Comment by kumarvna** [comment]
Thank you for reaching out. Yes. The Azure provider has added identity types with new releases and needs an update to the module.  Previously it only supports "SystemAssigned", and now managed identities are also possible to add. I will add this as soon as possible.

**Comment by Kumar1325** [comment]
@kumarvna may I know when can I expect this

I've a requirement to pass `null`/`false` value to it.

**Comment by kumarvna** [comment]
I will probably release it new version by Thursday.

**Comment by kumarvna** [comment]
This issue is now resolved.  Please use updated release v2.4.0 to provision resources. 
Thanks for the contribution.
